# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: yoink

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: mrmarble
    name: "{{ .ProjectName }}"

builds:
  - binary: "{{ .ProjectName }}"
    main: ./cmd/{{ .ProjectName }}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/mrmarble/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/mrmarble/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/mrmarble/{{ .ProjectName }}:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/mrmarble/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/mrmarble/{{ .ProjectName }}:latest-amd64
      - ghcr.io/mrmarble/{{ .ProjectName }}:latest-arm64v8
      - ghcr.io/mrmarble/{{ .ProjectName }}:latest-armv7

archives:
  - formats: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
