project_name: yoink

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: mrmarble
    name: "{{ .ProjectName }}"

builds:
  - binary: "{{ .ProjectName }}"
    main: ./cmd/{{ .ProjectName }}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64

    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"

    flags:
      - -trimpath

    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}

dockers:
  - image_templates:
      - "ghcr.io/mrmarble/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/mrmarble/{{ .ProjectName }}:v{{ .Major }}"
      - "ghcr.io/mrmarble/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/mrmarble/{{ .ProjectName }}:latest"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
