total_freeleech_size: "200GB" # Max space to use for downloads. If 0, no limit is applied
category: "FreeLeech" # Category to use for downloads.
paused: true # Whether to pause torrents after adding them to qBittorrentf
qbittorrent: # Connection details for qBittorrent
  host: "http://localhost:8080"
  username: "admin"
  password: "adminadmin"
prowlarr: # Connection details for Prowlarr
  host: "http://localhost:8081"
  api_key: "1234567890"
indexers: # List of indexers to use. Filters out any indexers not in this list
- id: 1 # ID of the indexer in Prowlarr
  max_seeders: 20 # Maximum number of seeders to allow. 0 = no limit
  max_size: "50GB" # Maximum file size to allow. 0 = no limit
  min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
- id: 3 # ID of the indexer in Prowlarr
  max_seeders: 10 # Maximum number of seeders to allow. 0 = no limit
  max_size: "50GB" # Maximum file size to allow. 0 = no limit
  min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
