version: "3"

dotenv: [".env"]

env:
  GCO_ENABLED: 0
tasks:
  run:
    cmds:
      - go run ./cmd/yoink {{.CLI_ARGS}}
  lint:
    cmds:
      - golangci-lint run --fix
  test:
    cmds:
      - go test -coverprofile=coverage.txt -covermode=atomic ./...
  goreleaser:
    desc: Run GoReleaser either in snapshot or release mode
    vars:
      SNAPSHOT:
        sh: 'if [[ $GITHUB_REF != refs/tags/v* ]]; then echo "--snapshot"; fi'
    cmds:
      - goreleaser release --clean {{.SNAPSHOT}}
  release:
    desc: Create a new tag
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin --tags
